pipeline{
    agent any
    tools{
        maven "maven"

    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Mieres7/AutoFix-EV1-Backend']])
                dir("backend/autofix"){
                bat "mvn clean install -DskipTests"
                }
            }
        }
        stage("Test"){
            steps{
                 dir("backend/autofix"){
                 bat "mvn test"
                 }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            dir("backend/autofix"){
                            bat "docker build -t mieres/autofix-backend:latest ."
                            bat "docker push mieres/autofix-backend:latest"
                            }
                        }
                }
            }
        }
    }
}